admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

admin_admin:
    resource: "@AdminAdminBundle/Resources/config/routing.yml"
    prefix:   /

app_bundle:
  prefix: /
  resource: '@AppBundle/Resources/config/routing.yml'
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
