admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

app_bundle:
  prefix: /
  resource: '@AppBundle/Resources/config/routing.yml'
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
